version: '3.5'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: postgres-type
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-type
    env_file:
      - .env
    ports:
      - '3003:3003'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
